library(tinytest)

coords_t <- create_coords_t_square(
  epsg = 2056,
  extent = terra::ext(c(
    xmin = 2697000,
    xmax = 2698000,
    ymin = 1252000,
    ymax = 1253000
  )),
  resolution = 100
)

expect_inherits(coords_t, "coords_t")
expect_stdout(print(coords_t), "Coordinate Table")
expect_equal(nrow(coords_t), 100L)
expect_true(all(
  c("id_coord", "lon", "lat") %in% names(coords_t)
))

# The stored fixture is generated by data-raw/test_fixtures.R, which is not run during
# checks; this guards against R/sysdata.rda going stale after a create_coords_t_square
# change.
expect_equal(
  create_coords_t_square(
    epsg = 2056,
    extent = terra::ext(c(
      xmin = 2697000,
      xmax = 2700000,
      ymin = 1252000,
      ymax = 1255000
    )),
    resolution = 100
  ),
  evoland:::test_coords_t
)
