library(tinytest)

expect_silent(
  lulc_data_t <- as_lulc_data_t(data.frame(
    id_coord = integer(),
    id_lulc = integer(),
    id_period = integer()
  ))
)
expect_stdout(print(lulc_data_t), "LULC Data Table \\(empty\\)")
expect_equal(nrow(lulc_data_t), 0L)

synthetic_lulc_data_t <- data.table::data.table(
  id_run = 0L,
  id_coord = c(1L, 2L, 1L),
  id_lulc = c(1L, 2L, 3L),
  id_period = c(1L, 1L, 2L)
)

# Test successful conversion
expect_silent(
  converted_lulc_data_t <- as_lulc_data_t(synthetic_lulc_data_t)
)
expect_equal(nrow(converted_lulc_data_t), 3L)
expect_inherits(converted_lulc_data_t, "lulc_data_t")

# The stored fixture is generated by data-raw/test_fixtures.R, which is not run during
# checks; this guards against R/sysdata.rda going stale after an as_lulc_data_t change.
local({
  n_coords <- nrow(evoland:::test_coords_t)
  set.seed(42)
  expect_equal(
    as_lulc_data_t(data.table::rbindlist(list(
      data.table::data.table(
        id_run = 0L,
        id_coord = 1:n_coords,
        id_lulc = sample(1:2, n_coords, TRUE, c(0.7, 0.3)),
        id_period = 1L
      ),
      data.table::data.table(
        id_run = 0L,
        id_coord = 1:n_coords,
        id_lulc = sample(1:2, n_coords, TRUE, c(0.5, 0.5)),
        id_period = 2L
      ),
      data.table::data.table(
        id_run = 0L,
        id_coord = 1:n_coords,
        id_lulc = sample(1:2, n_coords, TRUE, c(0.4, 0.6)),
        id_period = 3L
      )
    ))),
    evoland:::test_lulc_data_t
  )
})
