# Config for graphs and tables being produced
reporting:
  scenario_name: Naturalistic Futuristic Framework No. 1
  shortname: nff_no1
  # Should the datetime be included in output? Not relevant for publication, but very handy
  # when you're experimenting
  include_datetime: true
  authors:
    - Thing One
    - Thing Two

# Define the reference coordinates; may eventually be expanded to handle more general coordinate sources
coords:
  type: square # could also be hexagonal or triangular or polygon
  epsg: 2056 # also provides the unit
  extent: # where x = longitude, y = latitude
    xmin: 2480000
    xmax: 2481000
    ymin: 1070000
    ymax: 1071000
  resolution: 100 # unit according to EPSG; would be 100m in CH1903+ / LV95

lulc_data:
  # https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/geostat/geodaten-bundesstatistik/boden-nutzung-bedeckung-eignung/arealstatistik-schweiz.html
  provider: Arealstatistik
  sources:
    - url: https://dam-api.bfs.admin.ch/hub/api/dam/assets/32376216/appendix
      md5sum: c32937eb4a11fc9c5c58c66e9830360a

# Define the classes in use in the model; the src_classes in this example is from the 72
# categories used by the Arealstatistik
lulc_classes:
  # key "closed_forest": internal name
  closed_forest:
    # pretty name for reporting
    pretty_name: Dense Forest
    description: Normal forest; Forest strips; Afforestations; Felling areas; Brush forest
    # src_classes: list of underlying classes. if the LULC data source does not require
    # src_classes, this parameter can be left off.
    src_classes:
      - 50
      - 51
      - 52
      - 53
      - 57
  arable:
    pretty_name: Arable Land
    src_classes:
      - 41
  urban:
    pretty_name: Urban areas
    description: >
      Industrial and commercial buildings; Surroundings of industrial and commercial buildings;
      One- and two-family houses; Surroundings of one- and two-family houses;
      Terraced houses; Surroundings of terraced houses;
      Blocks of flats; Surroundings of blocks of flats;
      Public buildings; Surroundings of public buildings;
      Agricultural buildings; Surroundings of agricultural buildings;
      Unspecified buildings; Surroundings of unspecified buildings;
      Parking areas; Construction sites; Unexploited urban areas;
      Public parks; Sports facilities;
      Golf courses; Camping areas; Garden allotments; Cemeteries
    src_classes:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 19
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
  # Questionable: do we need a "static" class if this is conceptually very close to
  # setting the class to NA / NULL? essentially, we're saying "we know there is a class
  # here, so it's not nothing, but we also cannot apply useful transitions to it in the
  # future"
  static:
    pretty_name: Static / immutable classes
    description: >
      Motorways; Green motorway environs; Roads and paths; Green road environs; 
      Sealed railway areas; Green railway environs; 
      Airports; Airfields, green airport environs; 
      Energy supply plants; Waste water treatment plants; Other supply or waste treatment plants;
      Dumps; Quarries, mines; 
      Lakes; Rivers; Flood protection structures; Avalanche and rockfall barriers; 
      Wetlands; Alpine sports facilities; Rocks; Screes, sand; Landscape interventions
    src_classes:
      - 15
      - 16
      - 17
      - 18
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 61
      - 62
      - 63
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71

pred_data:
  noise:
    unit: dBa
    pretty_name: Maximum noise exposure
    orig_format: 10m*10m raster
    description: The maximum across all sonBASE noise exposure categories, i.e. daytime & nighttime road & rail exposure
    sources:
      - url: https://data.geo.admin.ch/ch.bafu.laerm-strassenlaerm_tag/laerm-strassenlaerm_tag/laerm-strassenlaerm_tag_2056.tif
        md5sum: a4b9f1c04ee63824f18852bfd1eecbdd
      - url: https://data.geo.admin.ch/ch.bafu.laerm-bahnlaerm_nacht/laerm-bahnlaerm_nacht/laerm-bahnlaerm_nacht_2056.tif
        md5sum: 4b782128495b5af8467e2259bd57def2
  distance_to_lake:
    unit: m
    pretty_name: Distance to closest lake
    format: vector
    description: Derived from swissTLM3D
    sources:
      - url: https://data.geo.admin.ch/ch.swisstopo.swisstlm3d/swisstlm3d_2025-03/swisstlm3d_2025-03_2056_5728.gpkg.zip
        md5sum: ecb3bcfbf6316c6e7542e20de24f61b7

# Settings for transition modelling
transitions:
  inclusion_threshold: 0.005 # fraction of class area needed to have changed to make modeling worthwhile
  predictor_neighborhoods: # Set up pythagorean matrices to represent stochasticity in neighborhood relations
    nhood_sizes: # Neighborhood sizes to assess - may be better expressed in units of length?
      - 3
      - 5
      - 7
    seed: 1234 # Ensures determinism
  predictor_selection:
    colinearity_threshold: 0.2
    colinearity_method: GLM
  disallowed: # disallowed transitions: where logic forbids transitions. can use yaml ~ or null for "any"
    - from: water
      to: ~
    - from: ~
      to: water
    - from: static
      to: ~

periods:
  # Periods are declared independently of lulc or predictor data. Either nearest neighbor or linear
  # interpolation is used to associate empirical data to these idealized dates.
  period_length: P5Y
  start_observed: 1990-01-01
  end_observed: 2020-01-01
  end_extrapolated: 2060-12-01

# Settings for interventions (altering probabilities, overriding allocations)
interventions:
  protected_areas: # name is tied to logic that reads these parameters
    pre_allocation: true
    pretty_name: Nature protection areas
    description: >
      This intervention introduces additional protected areas (PAs);
      urbanisation or agricultural expansion is prohibited within a PA once established.
    start_intervention: 2045-01-01
    end_intervention: 2060-01-01
    transitions:
      - 1
      - 2
    sources:
      - url: file:///somedir/protected_areas.gpkg
        md5sum: something
  glaciers:
    pre_allocation: false
    pretty_name: Deglaciation
    description: Deterministic transitions based on GloGEM
    sources:
      # An intervention may read from a set of files.
      # The temporal evolution expressed here could also be (more reliably) be expressed
      # in a netcdf/hdf
      - url: file:///somedir/glacier_extent_2030.tif
        md5sum: something
      - url: file:///somedir/glacier_extent_2040.tif
        md5sum: something
      - url: file:///somedir/glacier_extent_2050.tif
        md5sum: something
      - url: file:///somedir/glacier_extent_2060.tif
        md5sum: something
  hydro_predictors:
    pre_allocation: true
    # An intervention may also just use existing predictor data
    pretty_name: Hydrological predictor variables
    description: Provide refined predictor variables based on the rsplash hydrological model.
    params:
      tmpdir: /mnt/ramdisk
