# Config for graphs and tables being produced
reporting:
  scenario_name: Naturalistic Futuristic Framework No. 1
  shortname: nff_no1
  # Should the datetime be included in output? Not relevant for publication, but very handy
  # when you're experimenting
  include_datetime: true
  authors:
    - Thing One
    - Thing Two

# Define the reference coordinates; may eventually be expanded to handle more general coordinate sources
coords:
  type: square # could also be hexagonal or triangular or polygon
  epsg: 2056 # also provides the unit
  extent: # where x = longitude, y = latitude
    xmin: 2480000
    xmax: 2840000
    ymin: 1070000
    ymax: 1300000
  resolution: 100 # unit according to EPSG; would be 100m in CH1903+ / LV95

lulc_data:
  # Eventually you would choose your data provider here, but let's assume it's the Arealstatistik for now
  source:
    - url: https://dam-api.bfs.admin.ch/hub/api/dam/assets/32376216/appendix
      md5sum: c32937eb4a11fc9c5c58c66e9830360a

# Define the classes in use in the model
lulc_classes:
  # key "forest": internal name
  forest:
    # pretty name for reporting
    pretty_name: Forest
    # aggregation: list of underlying classes. if the LULC data source does not require
    # aggregation, this parameter can be left off.
    aggregation:
      - 1
      - 2
      - 3
      - 4
  arable:
    pretty_name: Arable Land
    aggregation:
      - 4
      - 6
  water:
    pretty_name: Lakes and Rivers
    aggregation:
      - 8
      - 9
  # Questionable: do we need an "other" class if this is conceptually very close to
  # setting the class to NA / NULL? essentially, we're saying "we know there is a class
  # here, so it's not nothing, but we also cannot apply useful transitions to it in the
  # future"
  other:
    pretty_name: Other Classes
    aggregation:
      - 12
      - 13
      - 14
      - 49

pred_data:
  noise:
    unit: dBa
    pretty_name: Maximum noise exposure
    source:
      - url: https://data.geo.admin.ch/ch.bafu.laerm-strassenlaerm_tag/laerm-strassenlaerm_tag/laerm-strassenlaerm_tag_2056.tif
        md5sum: something
      - url: https://data.geo.admin.ch/ch.bafu.laerm-bahnlaerm_nacht/laerm-bahnlaerm_nacht/laerm-bahnlaerm_nacht_2056.tif
        md5sum: somethingelse

# Settings for transition modelling
transitions:
  inclusion_threshold: 0.005 # fraction of class area needed to have changed to make modeling worthwhile
  predictor_neighborhoods: # Set up pythagorean matrices to represent stochasticity in neighborhood relations
    nhood_sizes: # Neighborhood sizes to assess - may be better expressed in units of length?
      - 3
      - 5
      - 7
    seed: 1234 # Ensures determinism
  predictor_selection:
    colinearity_threshold: 0.2
    colinearity_method: GLM
  disallowed: # disallowed transitions: where logic forbids transitions
    water: other # water to other
    other: forest # other to forest, see comment if an explicit "other" class is a good concept

periods:
  # Periods are declared independently of lulc or predictor data. Either nearest neighbor or linear
  # interpolation is used to associate empirical data to these idealized dates.
  period_length: P5Y
  start_observed: 1990-01-01
  end_observed: 2020-01-01
  end_extrapolated: 2060-12-01

# Settings for interventions (altering probabilities, overriding allocations)
interventions_pre_allocation:
  protected_areas: # name is tied to logic that reads these parameters
    pretty_name: Nature protection areas
    masks:
      - $cachedir/protected_areas.gpkg
  glaciers:
    pretty_name: Deglaciation
    id_scenariomip: SSP1-2.6
    masks:
      # An intervention may read from a set of files.
      # The temporal evolution expressed here could also be (more reliably) be expressed
      # in a netcdf/hdf
      - $cachedir/glacier_extent_2020.tif
      - $cachedir/glacier_extent_2030.tif
      - $cachedir/glacier_extent_2040.tif
  forest_expansion:
    # An intervention may also just use existing predictor data
    pretty_name: Ecohydrological Covariates
