# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_neighbors_cpp <- function(coords_t, max_distance, breaks, resolution = 100.0, calculate_distance = TRUE) {
    .Call(`_evoland_distance_neighbors_cpp`, coords_t, max_distance, breaks, resolution, calculate_distance)
}

