# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

raster_neighbors_cpp <- function(nrow, ncol) {
    .Call(`_evoland_raster_neighbors_cpp`, nrow, ncol)
}

gart_cpp <- function(P, states) {
    .Call(`_evoland_gart_cpp`, P, states)
}

sample_lognorm_area_cpp <- function(area_mean, area_var) {
    .Call(`_evoland_sample_lognorm_area_cpp`, area_mean, area_var)
}

sample_normal_area_cpp <- function(area_mean, area_var) {
    .Call(`_evoland_sample_normal_area_cpp`, area_mean, area_var)
}

grow_patch_cpp <- function(landscape, ant_landscape, probs, nbr_above, nbr_below, nbr_left, nbr_right, pivot, target_area, from_class, to_class, elongation, ncol, avoid_aggregation = FALSE) {
    .Call(`_evoland_grow_patch_cpp`, landscape, ant_landscape, probs, nbr_above, nbr_below, nbr_left, nbr_right, pivot, target_area, from_class, to_class, elongation, ncol, avoid_aggregation)
}

allocate_clumpy_cpp <- function(landscape, nrow, ncol, trans_from, trans_to, probs, area_mean, area_var, elongation, target_rate, method, batch_size, rarefy, shuffle, avoid_aggregation, area_dist) {
    .Call(`_evoland_allocate_clumpy_cpp`, landscape, nrow, ncol, trans_from, trans_to, probs, area_mean, area_var, elongation, target_rate, method, batch_size, rarefy, shuffle, avoid_aggregation, area_dist)
}

calculate_class_stats_cpp <- function(mat, cellsize) {
    .Call(`_evoland_calculate_class_stats_cpp`, mat, cellsize)
}

distance_neighbors_cpp <- function(coords_t, max_distance, quiet = FALSE) {
    .Call(`_evoland_distance_neighbors_cpp`, coords_t, max_distance, quiet)
}
