# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rook-adjacency neighbour indices for a raster (C++)
#'
#' @param nrow,ncol Raster dimensions.
#' @return Named list `above`/`below`/`left`/`right`, each a 1-based cell index
#'   per cell (row-major) with 0 meaning "no neighbour" (edge).
#' @keywords internal
raster_neighbors_cpp <- function(nrow, ncol) {
    .Call(`_evoland_raster_neighbors_cpp`, nrow, ncol)
}

#' Generalized Allocation Rejection Test (GART / MuST) in C++
#'
#' Inverse-CDF multinomial draw of a final state per cell.  NaN and negative
#' probabilities are clamped to 0 (matching the reference `clumpy` Python).
#'
#' @param P Numeric matrix (n_cells x n_states); each row should sum to ~1
#'   (include the "stay" column).
#' @param states Integer vector of length `ncol(P)` giving the state id of each
#'   column.
#' @return Integer vector of length `nrow(P)` with the sampled state per cell.
#' @keywords internal
gart_cpp <- function(P, states) {
    .Call(`_evoland_gart_cpp`, P, states)
}

#' Log-normal patch-area sampler (C++)
#'
#' @param area_mean Mean patch area (cells); NA / <= 0 returns 1.
#' @param area_var  Patch-area variance (cells^2); NA / <= 0 treated as 1.
#' @return Integer >= 1.
#' @keywords internal
sample_lognorm_area_cpp <- function(area_mean, area_var) {
    .Call(`_evoland_sample_lognorm_area_cpp`, area_mean, area_var)
}

#' Grow a single land-use patch from a pivot cell (C++)
#'
#' Thin wrapper around the internal patch grower, kept for direct use / unit
#' testing.  `landscape` is modified in place (allocated cells set to
#' `to_class`).  Neighbour vectors are 1-based with 0 == no neighbour, as
#' produced by [raster_neighbors_cpp()].
#'
#' @param landscape IntegerVector of current LULC values (NA_INTEGER = no-data).
#' @param ant_landscape IntegerVector of anterior (immutable) LULC values.
#' @param probs NumericVector of transition probabilities (length == landscape).
#' @param nbr_above,nbr_below,nbr_left,nbr_right Neighbour index vectors.
#' @param pivot 1-based pivot cell index.
#' @param target_area Target patch size (cells).
#' @param from_class,to_class Source/target LULC classes.
#' @param eccentricity Target elongation in \[0, 1\] (0 = isometric).
#' @param ncol Raster column count.
#' @return 1-based integer vector of allocated cell indices (incl. pivot), or
#'   empty if the pivot is not an available `from_class` cell.
#' @keywords internal
grow_patch_cpp <- function(landscape, ant_landscape, probs, nbr_above, nbr_below, nbr_left, nbr_right, pivot, target_area, from_class, to_class, eccentricity, ncol) {
    .Call(`_evoland_grow_patch_cpp`, landscape, ant_landscape, probs, nbr_above, nbr_below, nbr_left, nbr_right, pivot, target_area, from_class, to_class, eccentricity, ncol)
}

#' Run the CLUMPY allocation routine (C++)
#'
#' @description
#' Allocates LULC change for a single period.  See the file header for the
#' uSAM vs uPAM methods and the meaning of `batch_size` / `rarefy`.
#'
#' @param landscape IntegerVector of the anterior LULC state (row-major,
#'   1-based class ids, NA_INTEGER for no-data).  Not modified; a copy is
#'   returned with the allocated changes applied.
#' @param ant_landscape IntegerVector of the anterior state (immutable
#'   reference; a cell is only eligible as a pivot while both `landscape` and
#'   `ant_landscape` still equal its source class).
#' @param nrow,ncol Raster dimensions.
#' @param from_classes IntegerVector of anterior classes to process.
#' @param trans_from,trans_to IntegerVectors (length T) of the source/target
#'   class for each transition column of `probs`.
#' @param probs NumericMatrix (n_cells x T) of per-cell transition potentials,
#'   already adjusted/closed; column t corresponds to transition t.
#' @param area_mean,area_var,elongation NumericVectors (length T) of patch
#'   parameters per transition.
#' @param target_rate NumericVector (length T) of the target transition rate
#'   P(v|u) per transition (fraction of source pixels that change).  Used only
#'   by uPAM to set the per-transition pixel quota.
#' @param method 0 = uSAM (single pass), 1 = uPAM (iterative with quota).
#' @param batch_size uPAM only: pivots processed per GART re-draw (1 = strict
#'   uPAM, <= 0 = all candidates).
#' @param rarefy If TRUE, divide pivot probabilities by `area_mean` (the
#'   1/E(sigma) factor) so the allocated quantity of change matches the target.
#' @param shuffle If TRUE, randomise pivot processing order.
#' @return IntegerVector (length n_cells) of the posterior LULC state.
#' @keywords internal
allocate_clumpy_cpp <- function(landscape, ant_landscape, nrow, ncol, from_classes, trans_from, trans_to, probs, area_mean, area_var, elongation, target_rate, method, batch_size, rarefy, shuffle) {
    .Call(`_evoland_allocate_clumpy_cpp`, landscape, ant_landscape, nrow, ncol, from_classes, trans_from, trans_to, probs, area_mean, area_var, elongation, target_rate, method, batch_size, rarefy, shuffle)
}

distance_neighbors_cpp <- function(coords_t, max_distance, quiet = FALSE) {
    .Call(`_evoland_distance_neighbors_cpp`, coords_t, max_distance, quiet)
}

calculate_class_stats_cpp <- function(mat, cellsize) {
    .Call(`_evoland_calculate_class_stats_cpp`, mat, cellsize)
}

